### ISSUE TITLE
Can't connect to channels: always in the "joining" state

### ISSUE THREAD

**Issue by sotte** [jhosteny/occamy#3]
I'm trying to get occamy to work but the channels get stuck in the "joining" state.

[Here](https://github.com/sotte/python_channels/commits/master) is a minimal phoenix channel implementation which implements this: http://www.phoenixframework.org/docs/channels#section-tying-it-all-together. Just start the server `mix phoenix.server`.

[Here](https://github.com/sotte/occamy/blob/demo/demo.py) is the python client I'm using. `python demo.py` runs the client and you can see that the channel state is always "joining".

**Comment by sotte** [comment]
I debugged a bit. When manually setting `channel._state = "joined"` after the channel was joined the sent messages arrive at the server.

```
socket = Socket("ws://localhost:4000/socket")
socket.connect()

channel = Channel("rooms:lobby", {}, socket)
channel.on("new_msg", lambda msg: print(msg))
channel.join()
channel._state = "joined"
channel.push("new_msg", {"body": "test"})  # this msg arrives
```

**Comment by sotte** [comment]
Turns out I called the wrong function to create channels. Don't call `Channel` but `socket.channel`.

This works

```
socket = Socket("ws://localhost:4000/socket")
socket.connect()

channel = socket.channel("rooms:lobby", {})
channel.on("new_msg", lambda msg, x: print(msg, x))

channel.join()
```

**Comment by jhosteny** [comment]
@sotte Thanks for the PRs! I merged all of them.

I put this project together as a quick prototype to justify using Phoenix for a larger project, so if there are larger changes you would like to make I'm certainly happy to accept them.

**Comment by jhosteny** [comment]
@sotte I fixed one other minor typo from on of the PRs. I tried the demo against your sample phoenix app. I can see the message coming in on the phoenix app's console via the IO.puts (in the channel), but I don't see it on the webpage. I didn't have time to look into it more this morning, but I'm guessing it may just be something in that app then.

**Comment by sotte** [comment]
Hey @jhosteny, thanks for merging! And great to hear that PRs are welcome!

I also pushed a working chat client. I'm actually not sure what the problem was. Maybe the refactoring helped, maybe I changed the code. Anyway, now there you can chat with multiple python clients. See #11.

I'm also thinking about using phoenix for a larger project. I'll probably have to push lot's of data (protobuf or capnp) down the pipe. So I'll try that next.

If you know of any missing features of occamy can you please create tickets that describe them. I might have some time at hand to work on occamy.
